In [3]:
import numpy as np
import pandas as pd

In [31]:
data=np.arange(24).reshape(8,3)

In [33]:
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [15]:
type(data)

numpy.ndarray

In [17]:
#arrange built in function generate elements according to your number of elements length only for numeric

In [55]:
data=np.arange(30,60).reshape(5,6)

In [57]:
data

array([[30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59]])

In [49]:
data.shape

(5, 6)

In [51]:
#2 dimension rows and errors (2 brackets) if 3 or 4 dimension than multiple brackets8
data.ndim

2

In [89]:
# 20 and 10 are range and 10 is breaking it equally(Split your data in equal parts)
data2=np.linspace(20,10,10)

In [91]:
data2

array([20.        , 18.88888889, 17.77777778, 16.66666667, 15.55555556,
       14.44444444, 13.33333333, 12.22222222, 11.11111111, 10.        ])

In [93]:
#Calling random num (int)
np.random.randint(10)

6

In [99]:
#data frame= series + series (series=column). (indexes, rows and columns)
df=pd.DataFrame(data)

In [101]:
df

0   1   2   3   4   5
0  30  31  32  33  34  35
1  36  37  38  39  40  41
2  42  43  44  45  46  47
3  48  49  50  51  52  53
4  54  55  56  57  58  59

In [109]:
#whenever we work on pandas we will work on tabular(rows and data)
df=pd.DataFrame(data,index=['row1','row2','row3','row4','row5'],
columns=['column1','column2','column3','column4','column5','column6'])

In [111]:
df

column1  column2  column3  column4  column5  column6
row1       30       31       32       33       34       35
row2       36       37       38       39       40       41
row3       42       43       44       45       46       47
row4       48       49       50       51       52       53
row5       54       55       56       57       58       59

In [117]:
df.columns

Index(['column1', 'column2', 'column3', 'column4', 'column5', 'column6'], dtype='object')

In [119]:
df.shape

(5, 6)

In [135]:
df.head(2)

column1  column2  column3  column4  column5  column6
row1       30       31       32       33       34       35
row2       36       37       38       39       40       41

In [133]:
df.tail(3)

column1  column2  column3  column4  column5  column6
row3       42       43       44       45       46       47
row4       48       49       50       51       52       53
row5       54       55       56       57       58       59

In [131]:
#this will give random rows () if empty than it will bring 1 rows..(3)
df.sample(3)

column1  column2  column3  column4  column5  column6
row1       30       31       32       33       34       35
row3       42       43       44       45       46       47
row5       54       55       56       57       58       59

In [146]:
#provides complete summary
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int32
 1   column2  5 non-null      int32
 2   column3  5 non-null      int32
 3   column4  5 non-null      int32
 4   column5  5 non-null      int32
 5   column6  5 non-null      int32
dtypes: int32(6)
memory usage: 160.0+ bytes


In [144]:
#describe
df.describe()

column1    column2    column3    column4    column5    column6
count   5.000000   5.000000   5.000000   5.000000   5.000000   5.000000
mean   42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
std     9.486833   9.486833   9.486833   9.486833   9.486833   9.486833
min    30.000000  31.000000  32.000000  33.000000  34.000000  35.000000
25%    36.000000  37.000000  38.000000  39.000000  40.000000  41.000000
50%    42.000000  43.000000  44.000000  45.000000  46.000000  47.000000
75%    48.000000  49.000000  50.000000  51.000000  52.000000  53.000000
max    54.000000  55.000000  56.000000  57.000000  58.000000  59.000000

In [152]:
data={
    'App' : [f'App_{i}'for i in range(1,31)],
    'Category' : np.random.choice(['Game','Productivity','Health','Education'],30),
    'Rating' : np.random.uniform(1.0,5.0,30).round(1),
    'Reviews' : np.random.randint(1,10000,30),
    'Size' : np.random.choice(['Varies with device','10M','20M','30M'],30),
    'Installs' : np.random.choice(['1000+','10000+','50000+','100000+'],30),
    'Type': np.random.choice(['Free','Paid'],30),
    'Price': np.random.choice(['0','0.99','1.99','2.99','4.99','5.99','9.99'],30),
    'Content Rating' : np.random.choice(['Everyone','Teen','Everyone 10+','Mature'],30)
}

In [158]:
type(data)

dict

In [160]:
df=pd.DataFrame(data)

In [162]:
df

App      Category  Rating  Reviews                Size Installs  Type  \
0    App_1        Health     4.5     7036                 20M   50000+  Free   
1    App_2  Productivity     3.3     4570                 10M  100000+  Paid   
2    App_3          Game     2.1     4518  Varies with device   50000+  Free   
3    App_4     Education     3.3     7826                 30M    1000+  Paid   
4    App_5        Health     2.1     6385                 30M   50000+  Free   
5    App_6     Education     1.9     4572  Varies with device    1000+  Free   
6    App_7          Game     2.6     9687  Varies with device  100000+  Free   
7    App_8        Health     2.7     7361  Varies with device  100000+  Free   
8    App_9          Game     3.6     6869                 30M   10000+  Free   
9   App_10     Education     4.9     2230                 20M   50000+  Free   
10  App_11  Productivity     1.3     2477  Varies with device   50000+  Free   
11  App_12  Productivity     4.7     9735                 10M  100000+  Paid   
12  App_13          Game     4.2     7690                 20M   10000+  Free   
13  App_14  Productivity     2.1     3846                 10M   50000+  Free   
14  App_15          Game     1.8     6316                 10M   50000+  Free   
15  App_16     Education     3.5     3551                 20M   50000+  Free   
16  App_17  Productivity     2.7     9740                 20M   50000+  Free   
17  App_18        Health     3.3     7732                 10M   10000+  Free   
18  App_19          Game     4.9     4445                 20M   10000+  Paid   
19  App_20        Health     2.0      606                 10M  100000+  Paid   
20  App_21          Game     2.7     5730  Varies with device   10000+  Paid   
21  App_22          Game     2.4     1447                 20M   10000+  Free   
22  App_23          Game     4.1     3580  Varies with device   50000+  Free   
23  App_24     Education     1.7     6230  Varies with device   10000+  Paid   
24  App_25     Education     4.7     6435  Varies with device  100000+  Free   
25  App_26  Productivity     5.0     9559                 20M   10000+  Paid   
26  App_27     Education     2.8     9589  Varies with device   50000+  Paid   
27  App_28     Education     2.3     4815                 30M    1000+  Paid   
28  App_29     Education     4.2     6861                 20M  100000+  Free   
29  App_30          Game     3.3     4790                 10M   10000+  Free   

   Price Content Rating  
0   4.99   Everyone 10+  
1   9.99       Everyone  
2      0           Teen  
3   2.99       Everyone  
4   0.99   Everyone 10+  
5   1.99   Everyone 10+  
6   5.99         Mature  
7   9.99   Everyone 10+  
8   1.99           Teen  
9   2.99           Teen  
10     0           Teen  
11  5.99           Teen  
12     0         Mature  
13  2.99         Mature  
14  9.99         Mature  
15  2.99         Mature  
16  0.99   Everyone 10+  
17  5.99           Teen  
18  9.99       Everyone  
19  0.99   Everyone 10+  
20  1.99         Mature  
21  9.99   Everyone 10+  
22  9.99           Teen  
23  1.99   Everyone 10+  
24     0           Teen  
25  5.99           Teen  
26  0.99       Everyone  
27  0.99       Everyone  
28  9.99       Everyone  
29  9.99       Everyone

In [164]:
type(df)

pandas.core.frame.DataFrame

In [166]:
type(df.App)

pandas.core.series.Series

In [168]:
df.head(10)

App      Category  Rating  Reviews                Size Installs  Type  \
0   App_1        Health     4.5     7036                 20M   50000+  Free   
1   App_2  Productivity     3.3     4570                 10M  100000+  Paid   
2   App_3          Game     2.1     4518  Varies with device   50000+  Free   
3   App_4     Education     3.3     7826                 30M    1000+  Paid   
4   App_5        Health     2.1     6385                 30M   50000+  Free   
5   App_6     Education     1.9     4572  Varies with device    1000+  Free   
6   App_7          Game     2.6     9687  Varies with device  100000+  Free   
7   App_8        Health     2.7     7361  Varies with device  100000+  Free   
8   App_9          Game     3.6     6869                 30M   10000+  Free   
9  App_10     Education     4.9     2230                 20M   50000+  Free   

  Price Content Rating  
0  4.99   Everyone 10+  
1  9.99       Everyone  
2     0           Teen  
3  2.99       Everyone  
4  0.99   Everyone 10+  
5  1.99   Everyone 10+  
6  5.99         Mature  
7  9.99   Everyone 10+  
8  1.99           Teen  
9  2.99           Teen

In [170]:
df.tail(10)

App      Category  Rating  Reviews                Size Installs  Type  \
20  App_21          Game     2.7     5730  Varies with device   10000+  Paid   
21  App_22          Game     2.4     1447                 20M   10000+  Free   
22  App_23          Game     4.1     3580  Varies with device   50000+  Free   
23  App_24     Education     1.7     6230  Varies with device   10000+  Paid   
24  App_25     Education     4.7     6435  Varies with device  100000+  Free   
25  App_26  Productivity     5.0     9559                 20M   10000+  Paid   
26  App_27     Education     2.8     9589  Varies with device   50000+  Paid   
27  App_28     Education     2.3     4815                 30M    1000+  Paid   
28  App_29     Education     4.2     6861                 20M  100000+  Free   
29  App_30          Game     3.3     4790                 10M   10000+  Free   

   Price Content Rating  
20  1.99         Mature  
21  9.99   Everyone 10+  
22  9.99           Teen  
23  1.99   Everyone 10+  
24     0           Teen  
25  5.99           Teen  
26  0.99       Everyone  
27  0.99       Everyone  
28  9.99       Everyone  
29  9.99       Everyone

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   App             30 non-null     object 
 1   Category        30 non-null     object 
 2   Rating          30 non-null     float64
 3   Reviews         30 non-null     int32  
 4   Size            30 non-null     object 
 5   Installs        30 non-null     object 
 6   Type            30 non-null     object 
 7   Price           30 non-null     object 
 8   Content Rating  30 non-null     object 
dtypes: float64(1), int32(1), object(7)
memory usage: 2.1+ KB


In [176]:
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.156667  5874.266667
std     1.107244  2527.710453
min     1.300000   606.000000
25%     2.150000  4463.250000
50%     3.050000  6273.000000
75%     4.175000  7607.750000
max     5.000000  9740.000000

In [178]:
df.sample()

App      Category  Rating  Reviews Size Installs  Type Price  \
11  App_12  Productivity     4.7     9735  10M  100000+  Paid  5.99   

   Content Rating  
11           Teen

In [188]:
#cant call multiple columns (as this is 2d data) you have to bring double bracket for 2d data
df[['App','Price','Reviews']]

App Price  Reviews
0    App_1  4.99     7036
1    App_2  9.99     4570
2    App_3     0     4518
3    App_4  2.99     7826
4    App_5  0.99     6385
5    App_6  1.99     4572
6    App_7  5.99     9687
7    App_8  9.99     7361
8    App_9  1.99     6869
9   App_10  2.99     2230
10  App_11     0     2477
11  App_12  5.99     9735
12  App_13     0     7690
13  App_14  2.99     3846
14  App_15  9.99     6316
15  App_16  2.99     3551
16  App_17  0.99     9740
17  App_18  5.99     7732
18  App_19  9.99     4445
19  App_20  0.99      606
20  App_21  1.99     5730
21  App_22  9.99     1447
22  App_23  9.99     3580
23  App_24  1.99     6230
24  App_25     0     6435
25  App_26  5.99     9559
26  App_27  0.99     9589
27  App_28  0.99     4815
28  App_29  9.99     6861
29  App_30  9.99     4790

In [192]:
df.describe()

Rating      Reviews
count  30.000000    30.000000
mean    3.156667  5874.266667
std     1.107244  2527.710453
min     1.300000   606.000000
25%     2.150000  4463.250000
50%     3.050000  6273.000000
75%     4.175000  7607.750000
max     5.000000  9740.000000

In [194]:
df.shape

(30, 9)

In [210]:
#To find total unique values (Filter)
df['Size'].unique()

array(['20M', '10M', 'Varies with device', '30M'], dtype=object)

In [212]:
df['Rating'].unique()

array([4.5, 3.3, 2.1, 1.9, 2.6, 2.7, 3.6, 4.9, 1.3, 4.7, 4.2, 1.8, 3.5,
       2. , 2.4, 4.1, 1.7, 5. , 2.8, 2.3])

In [214]:
df['Category'].unique()

array(['Health', 'Productivity', 'Game', 'Education'], dtype=object)

In [218]:
#To find null (your answer is in boolean)
df.isnull()

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0   False     False   False    False  False     False  False  False   
1   False     False   False    False  False     False  False  False   
2   False     False   False    False  False     False  False  False   
3   False     False   False    False  False     False  False  False   
4   False     False   False    False  False     False  False  False   
5   False     False   False    False  False     False  False  False   
6   False     False   False    False  False     False  False  False   
7   False     False   False    False  False     False  False  False   
8   False     False   False    False  False     False  False  False   
9   False     False   False    False  False     False  False  False   
10  False     False   False    False  False     False  False  False   
11  False     False   False    False  False     False  False  False   
12  False     False   False    False  False     False  False  False   
13  False     False   False    False  False     False  False  False   
14  False     False   False    False  False     False  False  False   
15  False     False   False    False  False     False  False  False   
16  False     False   False    False  False     False  False  False   
17  False     False   False    False  False     False  False  False   
18  False     False   False    False  False     False  False  False   
19  False     False   False    False  False     False  False  False   
20  False     False   False    False  False     False  False  False   
21  False     False   False    False  False     False  False  False   
22  False     False   False    False  False     False  False  False   
23  False     False   False    False  False     False  False  False   
24  False     False   False    False  False     False  False  False   
25  False     False   False    False  False     False  False  False   
26  False     False   False    False  False     False  False  False   
27  False     False   False    False  False     False  False  False   
28  False     False   False    False  False     False  False  False   
29  False     False   False    False  False     False  False  False   

    Content Rating  
0            False  
1            False  
2            False  
3            False  
4            False  
5            False  
6            False  
7            False  
8            False  
9            False  
10           False  
11           False  
12           False  
13           False  
14           False  
15           False  
16           False  
17           False  
18           False  
19           False  
20           False  
21           False  
22           False  
23           False  
24           False  
25           False  
26           False  
27           False  
28           False  
29           False

In [222]:
#you can use.sum to get the count of null
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
dtype: int64

In [228]:
df['Price'].unique()

array(['4.99', '9.99', '0', '2.99', '0.99', '1.99', '5.99'], dtype=object)

In [232]:
#Data cleansing (you have to check first then replace)
df['Price']=df['Price'].replace('Free','0')

In [234]:
df['Price']

0     4.99
1     9.99
2        0
3     2.99
4     0.99
5     1.99
6     5.99
7     9.99
8     1.99
9     2.99
10       0
11    5.99
12       0
13    2.99
14    9.99
15    2.99
16    0.99
17    5.99
18    9.99
19    0.99
20    1.99
21    9.99
22    9.99
23    1.99
24       0
25    5.99
26    0.99
27    0.99
28    9.99
29    9.99
Name: Price, dtype: object